name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Set VERSION
      id: versions
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Check VERSION
      env:
        RELEASE_VERSION: ${{ steps.versions.outputs.version }}
      run: |
        echo $RELEASE_VERSION

    - name: Set TAG
      id: tags
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check TAG
      env:
        RELEASE_TAG: ${{ steps.tags.outputs.tag }}
      run: |
        echo $RELEASE_TAG
  
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Check date
      env:
        DATE: ${{ steps.date.outputs.date }}
      run: |
        echo $DATE
  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.versions.outputs.version }}

    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.versions.outputs.version }}